Data provider apteka-911
Oleksandr-Eleks/pharmagator pull request #101
Opened 2021-11-18 12:23 UTC by ritalinch

2021-11-18 15:06 UTC, MuchosChuchos commented
1) So many files are changed that do not belong to your data source.
2) You have created interface HTMLParser and class SocialnaParser in the wrong package (dto??? Does parser belongs to dtos??)
If I have understood you correctly you create HTMLParser for SocialnaParser, but any class could have that interface. 

this is what catches the eye the first time.

2021-11-20 10:49 UTC, MuchosChuchos commented
I cannot understand the commits history at all

2021-11-23 13:32 UTC, VolodymyrHoliev approved these changes

2021-12-06 22:06 UTC, Oleksandr-Eleks requested changes

2021-12-06 22:06 UTC, Oleksandr-Eleks commented on api/src/main/resources/application.yaml
> +      page-limit: 10
Please limit to 5

2021-12-06 22:06 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/dataproviders/dto/socialna/parsers/SocialnaParserTestIT.java
> +}
Please add BL in the end

2021-12-06 22:06 UTC, Oleksandr-Eleks commented on api/src/test/resources/html/socialna-test-page.html
> +<!DOCTYPE html>
Please remove this file from this PR

2021-12-06 23:54 UTC, VolodymyrHoliev commented on api/src/test/resources/html/socialna-test-page.html
> +<!DOCTYPE html>
That's for testing. This provider is parsing html pages. I thought that it's not the best idea to hardcode html page as a string in test classes. Am I wrong and it's better to use plain strings instead?

2021-12-07 09:36 UTC, Oleksandr-Eleks commented on api/src/test/resources/html/socialna-test-page.html
> +<!DOCTYPE html>
My bad. 
This is good idea.

2021-12-08 03:41 UTC, VolodymyrHoliev commented on api/src/test/java/com/eleks/academy/pharmagator/dataproviders/dto/socialna/parsers/SocialnaParserTestIT.java
> +}
I have fixed this issues and made PR on Rita's branch. She'll update this PR a little bit later.

2021-12-13 15:58 UTC, VolodymyrHoliev commented on api/src/main/resources/application.yaml
> +      page-limit: 10
Fixed

2021-12-13 15:58 UTC, VolodymyrHoliev commented on api/src/test/java/com/eleks/academy/pharmagator/dataproviders/dto/socialna/parsers/SocialnaParserTestIT.java
> +}
Fixed

2021-12-15 14:00 UTC, Oleksandr-Eleks approved these changes

2021-12-15 14:04 UTC, Anna-Kudiakova approved these changes

2021-12-17 07:29 UTC, merged