Feature/pdf export
Oleksandr-Eleks/pharmagator pull request #118
Opened 2021-11-24 13:42 UTC by kolyaratishin

Add new feature – data export to pdf. Also wrote tests (#112)

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/services/PDFExportService.java
> +
Remove BL

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/services/PDFExportService.java
> +                .stream()
Please inline row 60 to upper

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/services/PDFExportService.java
> +        );
Please inline to prev. row

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ExportControllerIT.java
> +
Remove BL

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ExportControllerIT.java
> +
Remove BL

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/services/projections/MedicinePriceImpl.java
> +
Remove BL

2021-11-24 14:59 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/services/PDFExportServiceTest.java
> +        prices =
Inline with next row

2021-11-24 15:48 UTC, kolyaratishin commented on api/src/main/java/com/eleks/academy/pharmagator/services/PDFExportService.java
> +
done

2021-11-24 15:48 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/services/PDFExportServiceTest.java
> +        prices =
done

2021-11-24 15:48 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/services/projections/MedicinePriceImpl.java
> +
done

2021-11-24 15:49 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ExportControllerIT.java
> +
done

2021-11-24 15:49 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ExportControllerIT.java
> +
done

2021-11-24 15:49 UTC, kolyaratishin commented on api/src/main/java/com/eleks/academy/pharmagator/services/PDFExportService.java
> +                .stream()
done

2021-11-24 15:49 UTC, kolyaratishin commented on api/src/main/java/com/eleks/academy/pharmagator/services/PDFExportService.java
> +        );
done

2021-11-24 16:27 UTC, VolodymyrHoliev commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/GlobalExceptionHandler.java
> +    public ResponseEntity<String> springHandleExportExceptions(ExportExceptions ex){
Just one minor suggestion: please, rename this method to `handle(ExportExceptions ex)` . It thinks this would be enough because type of exception specified here: `@ExceptionHandler(ExportExceptions.class)` so we already know which exactly exception will be handled by spring. Just for better readability.

2021-11-24 16:29 UTC, VolodymyrHoliev approved these changes

2021-11-24 16:32 UTC, Anna-Kudiakova requested changes

2021-11-24 16:32 UTC, Anna-Kudiakova commented on api/src/test/java/com/eleks/academy/pharmagator/services/projections/MedicinePriceImpl.java
> +    }
for what did you override getters if you have Data annotation

2021-11-24 16:57 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/services/projections/MedicinePriceImpl.java
> +    }
Because without this. we will get compile error, because there are no implemented methods

2021-11-24 16:58 UTC, kolyaratishin commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/GlobalExceptionHandler.java
> +    public ResponseEntity<String> springHandleExportExceptions(ExportExceptions ex){
done

2021-11-24 17:30 UTC, Anna-Kudiakova approved these changes

2021-11-25 09:15 UTC, zyoneal approved these changes

2021-11-25 09:18 UTC, Oleksandr-Eleks approved these changes

2021-11-25 10:26 UTC, merged