Feature/csv export
Oleksandr-Eleks/pharmagator pull request #134
Opened 2021-11-29 13:34 UTC by kolyaratishin

I made it possible to export to csv (#113)

2021-11-29 14:48 UTC, VolodymyrHoliev approved these changes

2021-11-29 15:55 UTC, Anna-Kudiakova commented on api/src/test/java/com/eleks/academy/pharmagator/services/CsvServiceImplTest.java
> +        ));
these changes are not relevant to the topic of the pull request

2021-11-29 16:02 UTC, Anna-Kudiakova approved these changes

2021-11-29 16:06 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/services/CsvServiceImplTest.java
> +        ));
This test and this testClass was wrote bad and i had to change some fields and methods in order to fix it. Also, this test failed when I did the PR, so it had to be rewritten

2021-11-29 17:25 UTC, MuchosChuchos requested changes

2021-11-29 17:25 UTC, MuchosChuchos commented on api/src/test/resources/export/export.csv
> +Fervex,42.25,Liki24
add blank line. =)

2021-11-29 22:39 UTC, VolodymyrHoliev commented
@Anna-Kudiakova since you've approved this PR could you please resolve the conversations above?

2021-11-30 10:15 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/services/CsvServiceImplTest.java
> +        ));
>_<
I'm a bit confused that there is no real import.csv file.
Please test it on a real small file.

2021-11-30 10:15 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/services/CsvServiceImplTest.java
> +
Please remove BL

2021-11-30 10:19 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ExportControllerIT.java
> +        this.mockMvc.perform(MockMvcRequestBuilders.get(PDF_URI))
The same as prev.

2021-11-30 10:25 UTC, MuchosChuchos approved these changes

2021-11-30 12:54 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/services/CsvServiceImplTest.java
> +
done

2021-11-30 12:56 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/services/CsvServiceImplTest.java
> +        ));
It will be fixed in next PR

2021-11-30 12:57 UTC, merged