Pharmacy service & medicine service tests
Oleksandr-Eleks/pharmagator pull request #141
Opened 2021-12-03 11:20 UTC by MariamnaKh

2021-12-03 11:34 UTC, MuchosChuchos requested changes

2021-12-03 11:34 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/services/MedicineServiceImplTest.java
> +    public void givenMedicine_CreateNewMedicine() {
be consistent with names:
MethodName_StateUnderTest_ExpectedBehavior

2021-12-03 11:34 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/services/PharmacyServiceImplTest.java
> +    public void givenPharmacy_CreateNewPharmacy() {
the same, 
name test method.

2021-12-03 11:34 UTC, MuchosChuchos commented
fix code smells

2021-12-03 12:29 UTC, VolodymyrHoliev reviewed
Generally, it looks good. 
Please, consider change method's names(e.g. `getAllMedicines_ok`, `saveMedicine_validMedicine_ok` and so on), that's IMHO, of course.
IMHO it would be great to add some cases like `delete_notExistingMedicine_*`(* stands for what you're expecting: exception, null etc.) and so on. 
Please, try to avoid using `public` modifier in method signature. Basically, all you need to get rid of code smells is to remove this modifier(e.g. `void getAllMedicines()`).

2021-12-03 13:53 UTC, MariamnaKh commented
@VolodymyrHoliev  Yes, I have completely forgotten about public modifier

2021-12-03 15:31 UTC, VolodymyrHoliev approved these changes
Now it can be approved. 
I'm not sured about definition, but let's call it 'bad-path'( I mean tests like `findById_nonExistingId` and so on ) .
 Excluding bad-path won't affect the code coverage calculation, but if want to write really good tests it would be great to add those cases in corresponding IT.

2021-12-04 14:29 UTC, Anna-Kudiakova approved these changes

2021-12-05 16:44 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/services/PharmacyServiceImplTest.java
> +    public void givenPharmacy_CreateNewPharmacy() {
there is no one correct way to name test methods, therefore I believe that my way of doing it is worth existing. However, as we already have a pattern of doing it in our project, I changed the naming.

2021-12-05 16:44 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/services/MedicineServiceImplTest.java
> +    public void givenMedicine_CreateNewMedicine() {
K

2021-12-05 16:55 UTC, MariamnaKh commented
@VolodymyrHoliev I guess it will. That's great that you are trying to explain and give advice

2021-12-05 18:50 UTC, MuchosChuchos approved these changes

2021-12-05 18:50 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/services/MedicineServiceImplTest.java
> +    void deleteById_nonExistingId_throwsException() {
it would be great to specify that ex.

2021-12-05 18:50 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/services/PharmacyServiceImplTest.java
> +    void deleteById_nonExistingId_throwsException() {
same

2021-12-06 10:49 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/services/PharmacyServiceImplTest.java
> +    void deleteById_nonExistingId_throwsException() {
k

2021-12-06 10:51 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/services/MedicineServiceImplTest.java
> +    void deleteById_nonExistingId_throwsException() {
done, but that's exactly what you had to do when you created this method =)

2021-12-06 12:27 UTC, merged