External input feature
Oleksandr-Eleks/pharmagator pull request #145
Opened 2021-12-06 20:34 UTC by Anna-Kudiakova

2021-12-06 20:58 UTC, VolodymyrHoliev approved these changes

2021-12-06 22:04 UTC, Oleksandr-Eleks requested changes

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @GetMapping("/showForm")
Please follow naming conventions

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @PostMapping("/addMedicine")
Naming

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/main/resources/templates/addMedicine.html
> +
Please remove extra BL

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/main/resources/templates/addMedicine.html
> +
Please remove extra BL

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/main/resources/templates/result.html
> +
Please remove extra BL

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputControllerTest.java
> +
Please remove extra BL

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputControllerTest.java
> +
Please remove extra BL

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputControllerTest.java
> +
Please remove extra BL

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.get(BASE_URI+"/showForm"))
Formatting, naming

2021-12-06 22:04 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputControllerTest.java
> +
Please remove extra BL

2021-12-07 06:21 UTC, MuchosChuchos requested changes

2021-12-07 06:21 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @GetMapping({"", "/", "/index", "/index.html", "/home", "/homepage"})
wrong home path. I think it's ok to have home on "protocol://domain/", but not on "protocol://domain/input" and "protocol://domain/" at the same time.

2021-12-07 06:28 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @GetMapping({"", "/", "/index", "/index.html", "/home", "/homepage"})
It would nice to have input page just on "protocol://domain/input"

2021-12-07 06:31 UTC, MuchosChuchos requested changes

2021-12-07 06:31 UTC, MuchosChuchos commented on api/src/main/resources/templates/addMedicine.html
> +                                  oninvalid="this.setCustomValidity('Enter external id here, it should be positive integer')"
it shouldn't. Basically, EXTERNAL_ID prop can include any chars, e.g. NAZOLVIN_10ML_BOTLE or 234ARF4_23reAfAFAsd

2021-12-07 06:32 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @GetMapping({"", "/", "/index", "/index.html", "/home", "/homepage"})
You can show your forms like a different fragments, instead of pages.

2021-12-07 07:11 UTC, MuchosChuchos commented
Merging should be to front_end branch, instead of develop

2021-12-07 13:17 UTC, Anna-Kudiakova commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +
Done

2021-12-07 13:18 UTC, Anna-Kudiakova commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @GetMapping("/showForm")
Done

2021-12-07 13:18 UTC, Anna-Kudiakova commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.get(BASE_URI+"/showForm"))
Done

2021-12-07 13:19 UTC, Anna-Kudiakova commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/ui/ExternalInputController.java
> +    @GetMapping({"", "/", "/index", "/index.html", "/home", "/homepage"})
Fixed

2021-12-07 13:20 UTC, Anna-Kudiakova commented on api/src/main/resources/templates/addMedicine.html
> +                                  oninvalid="this.setCustomValidity('Enter external id here, it should be positive integer')"
Yes, agree, I fixed it

2021-12-07 13:44 UTC, MariamnaKh approved these changes

2021-12-07 15:22 UTC, MuchosChuchos approved these changes
Nice!        =)

2021-12-08 09:25 UTC, Oleksandr-Eleks approved these changes

2021-12-08 10:23 UTC, merged