Add upload csv file
Oleksandr-Eleks/pharmagator pull request #75
Opened 2021-11-10 16:08 UTC by zyoneal

2021-11-10 16:38 UTC, Oleksandr-Eleks reviewed
Please take to account that there will be some changes regarding Pharmacy name in imported Medicines.

2021-11-10 16:38 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +        if (!TYPE.equals(file.getContentType())) {
Please do not use inversion here. 
Try to use ternary operator here.

2021-11-10 16:59 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +    public ResponseEntity uploadCSVFile(@RequestParam("file") MultipartFile file) {
ResponseEntity is generic class.

2021-11-10 17:44 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +    public ResponseEntity uploadCSVFile(@RequestParam("file") MultipartFile file) {
Done

2021-11-10 17:44 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +        if (!TYPE.equals(file.getContentType())) {
Done

2021-11-10 18:49 UTC, MuchosChuchos requested changes

2021-11-10 18:49 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/dataproviders/dto/MedicineDto.java
>  public class MedicineDto {
take a look that medicineDTO has been changed, so you should fetch those changes and then do PR.

2021-11-10 18:49 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +    public ResponseEntity<ResponseMessage> uploadCSVFile(@RequestParam("file") MultipartFile file) {
Please create another endpoint for uploading multiple files

2021-11-10 18:49 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +        message = "Please upload a csv file!";
I can't understand that msg. Pls change msg to more understandable. Like "wrong file type" or smth like this

2021-11-10 18:49 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/view/ResponseMessage.java
> +    public String message;
public field with getter and setter?

2021-11-10 18:56 UTC, MuchosChuchos requested changes

2021-11-10 18:56 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +            BeanListProcessor<MedicineDto> rowProcessor = new BeanListProcessor<>(MedicineDto.class);
Pls extract those lines into a method that's setting up univocityparser

2021-11-10 18:56 UTC, MuchosChuchos commented on api/src/main/java/com/eleks/academy/pharmagator/view/ResponseMessage.java
> +public class ResponseMessage {
Change name pls. U should take notes down that is a class for CsvControler

2021-11-10 20:07 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +        message = "Please upload a csv file!";
Done

2021-11-10 20:07 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/dataproviders/dto/MedicineDto.java
>  public class MedicineDto {
Done

2021-11-10 20:08 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/view/ResponseMessage.java
> +    public String message;
Done

2021-11-10 20:08 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/view/ResponseMessage.java
> +public class ResponseMessage {
Done

2021-11-11 07:22 UTC, pavlosloboda requested changes

2021-11-11 07:22 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +            } catch (Exception e) {
Why do you need here this try-catch? csvService.save(file) can not throw any of the checked exceptions.

2021-11-11 07:22 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +        if (CsvHelper.hasCSVFormat(file)) {
It would be nice to move this validation to service and throw a specific exception if a format is wrong.

2021-11-11 07:22 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +            CsvParser parser = new CsvParser(settings);
Do we really need to construct a parser for each uploaded file? Would it be better to create a bean and inject it to service?

2021-11-11 07:22 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvService.java
> +            throw new RuntimeException("fail to store csv data: " + e.getMessage());
Please, avoid throwing Generic exceptions.
https://rules.sonarsource.com/java/RSPEC-112

2021-11-11 07:57 UTC, Oleksandr-Eleks commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +    public ResponseEntity<ResponseMessage> uploadCSVFile(@RequestParam("file") MultipartFile file) {
@MuchosChuchos please create an issue for it. It would be great to add new endpoint in a separate PR.

2021-11-11 10:47 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +        if (CsvHelper.hasCSVFormat(file)) {
Done

2021-11-11 11:08 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvService.java
> +            throw new RuntimeException("fail to store csv data: " + e.getMessage());
Done

2021-11-11 11:51 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +            CsvParser parser = new CsvParser(settings);
https://www.programcreek.com/java-api-examples/?api=com.univocity.parsers.csv.CsvParser

2021-11-11 14:28 UTC, pavlosloboda requested changes
My comments are marked as resolved but actually are not. Please check it again.

2021-11-13 13:28 UTC, kolyaratishin commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvService.java
> +                        .map(medicineDto -> this.modelMapper.map(medicineDto, Medicine.class))
Inappropriate saving, you should make it like in scheduler

2021-11-13 15:33 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvService.java
> +                        .map(medicineDto -> this.modelMapper.map(medicineDto, Medicine.class))
Done

2021-11-15 07:33 UTC, pavlosloboda requested changes

2021-11-15 07:33 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +        } catch (InvalidFileFormatException e) {
Please, handle this exception with ControllerAdvice

2021-11-15 07:33 UTC, pavlosloboda commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +            return new ArrayList<>();
I don't think it's a good idea to ignore Exception

2021-11-17 09:34 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +            return new ArrayList<>();
done

2021-11-17 09:34 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/controllers/UploadController.java
> +        } catch (InvalidFileFormatException e) {
done

2021-11-20 13:49 UTC, Oleksandr-Eleks approved these changes

2021-11-20 13:53 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/AppExceptionHandler.java
> +    public ResponseEntity<Object> handleInvalidFileFormatException(InvalidFileFormatException ex, WebRequest request) {
Unnecessary generification to `Object`. The return type is always `ResponseEntity<ApiError>`.

2021-11-20 13:54 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/AppExceptionHandler.java
> +@ControllerAdvice
`@RestControllerAdvice` is semantically more applicable here

2021-11-20 13:55 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/AppExceptionHandler.java
> +        return new ResponseEntity<>(new ApiError(ex.getMessage(), HttpStatus.BAD_REQUEST, LocalDateTime.now()), HttpStatus.BAD_REQUEST);
What is the purpose of `ApiError#httpStatus`? I can set `AriError#httpStatus -> 500`, but `ResponseEntity#status -> 400`

2021-11-20 14:01 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +        throw new AssertionError("Instantiating utility class.");
`UnsupportedOperationException`

2021-11-20 14:05 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +    static CsvParser getCsvParser(BeanListProcessor<MedicineDto> rowProcessor) {
Why don't tou expose this as a Spring Bean?

2021-11-20 14:23 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvService.java
> +    private final CsvParser parser = CsvHelper.getCsvParser(CsvHelper.getProcessor());
Why do you call 2 static methods from one class here? You can encapsulate this logic within `CsvHelper`.

But I'd prefer exposing `com.univocity.parsers.csv.CsvParser` as a bean in a configuration class and simply inject it here alongside the other components.

2021-11-20 14:25 UTC, sergvasylchak commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +            CsvParser parser = new CsvParser(settings);
And what's your point?)

> https://www.programcreek.com/java-api-examples/?api=com.univocity.parsers.csv.CsvParser

2021-11-21 12:34 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvService.java
> +    private final CsvParser parser = CsvHelper.getCsvParser(CsvHelper.getProcessor());
done

2021-11-21 12:34 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +    static CsvParser getCsvParser(BeanListProcessor<MedicineDto> rowProcessor) {
done

2021-11-21 12:35 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/services/CsvHelper.java
> +        throw new AssertionError("Instantiating utility class.");
done

2021-11-21 12:35 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/AppExceptionHandler.java
> +        return new ResponseEntity<>(new ApiError(ex.getMessage(), HttpStatus.BAD_REQUEST, LocalDateTime.now()), HttpStatus.BAD_REQUEST);
I do not understand

2021-11-21 12:35 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/AppExceptionHandler.java
> +@ControllerAdvice
done

2021-11-21 12:35 UTC, zyoneal commented on api/src/main/java/com/eleks/academy/pharmagator/exceptions/AppExceptionHandler.java
> +    public ResponseEntity<Object> handleInvalidFileFormatException(InvalidFileFormatException ex, WebRequest request) {
done

2021-11-23 19:21 UTC, Oleksandr-Eleks commented
Another version merged.

2021-11-23 19:21 UTC, closed without merging