add medicine test
Oleksandr-Eleks/pharmagator pull request #80
Opened 2021-11-11 19:18 UTC by MariamnaKh

2021-11-11 20:52 UTC, Oleksandr-Eleks requested changes

2021-11-11 20:52 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/MedicineControllerTest.java
> +                        contentType(MediaType.APPLICATION_JSON).
Please start new lines from dots

2021-11-11 20:52 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/MedicineControllerTest.java
> +    @BeforeEach
I don't see any modifications of those objects in tests. So, suppose it may be initialized once for whole test class.

2021-11-11 20:52 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/MedicineControllerTest.java
> +    @AfterEach
You may get rid of that method.

2021-11-11 21:28 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/MedicineControllerTest.java
> +                        contentType(MediaType.APPLICATION_JSON)).
done

2021-11-11 21:43 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/MedicineControllerTest.java
> +    @BeforeEach
done

2021-11-12 10:19 UTC, MariamnaKh commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/MedicineControllerTest.java
> +    public void DeleteById_ShouldDeleteMedicine() throws Exception {
that controller responds to a certain url, listen to a certain http request, and business logic is called as expected

2021-11-12 11:18 UTC, Oleksandr-Eleks approved these changes

2021-11-12 11:26 UTC, pavlosloboda approved these changes

2021-11-12 11:29 UTC, Anna-Kudiakova approved these changes

2021-11-12 11:38 UTC, merged