Add basic tests for PriceController
Oleksandr-Eleks/pharmagator pull request #87
Opened 2021-11-13 12:36 UTC by SofiiaOlenyn

**Issue**
[Add basic tests for PriceController #60](https://github.com/Oleksandr-Eleks/pharmagator/issues/60)

2021-11-13 19:00 UTC, Anna-Kudiakova requested changes

2021-11-16 11:22 UTC, MuchosChuchos requested changes

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
why so many valueOf()?

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        this.mockMvc = MockMvcBuilders
Could you pls be more consistent with this-refs?? in some cases you use it, in others you don't

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        verify(priceService).findAll();
Could you explain to me what you are doing here(85, 86 lines). I did not understand it.  PLS  ^-^

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                        .contentType(MediaType.APPLICATION_JSON))
GET method does not have any content(body)

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        mockMvc.perform(get(URI + URI_PRICE)
here and in line 138 not extracted value, but there are not extracted values in lines 107, 117, 130. Why?
(lines reside in that file)

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
make nice formatted those lines(117-120), pls

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .content(CONTENT)).andExpect(status().isNotFound());
same problem with lines to be formatted. andExpect should be on next line

2021-11-16 11:22 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +    void updatePharmacyById_NotFound() throws Exception {
Make that name of method more consistent, pls.

2021-11-16 11:50 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        this.mockMvc = MockMvcBuilders
what exactly do you mean?

2021-11-16 11:50 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        verify(priceService).findAll();
I check that when you ask "find all" the status will be OK (85) and the priceService will be called (86)

2021-11-16 12:00 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        mockMvc.perform(get(URI + URI_PRICE)
Because if entity is not found, it will not be returned, and there is no reason to value. If I understood correctly)

2021-11-16 12:04 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
because it's the only way it works :)

2021-11-16 13:58 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
are u sure?

2021-11-16 14:00 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        this.mockMvc = MockMvcBuilders
in some cases you use it(this-ref), in others you don't (use this-ref)

2021-11-16 14:02 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        verify(priceService).findAll();
you should expect the list of prices, so can add another 'andExpect'

2021-11-16 14:06 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        mockMvc.perform(get(URI + URI_PRICE)
not entirely correct, cause I've talked about incoming variables of the method 'get'.

2021-11-16 14:50 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
90% sure :)

2021-11-16 14:51 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        this.mockMvc = MockMvcBuilders
Ok, got it)

2021-11-16 15:25 UTC, kolyaratishin commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
Can you tell me why do you compare price, which has to be BigDecimal, with Integer.valueOf()?

2021-11-16 15:44 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
It is a good question.
I can't compare like this:
"$ .price", equalTo (priceDto.getPrice ()).
I also can't do this:
"$ .price", equalTo (BigDecimal.valueOf (priceDto.getPrice ())
So I have options like this:
1. "$ .price", equalTo (BigDecimal.valueOf (Long.valueOf (String.valueOf) (priceDto.getPrice ())))));
2. "$. Price", equalTo (Integer.valueOf (String.valueOf (priceDto.getPrice ())))
I have chosen the second one.
If u know another option, pls tell me ))

2021-11-16 16:07 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
did u try just priceDto.getPrice ().toString()

2021-11-16 16:27 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
In our case I don't see a big difference between String.valueOf(priceDto.getPrice()) and priceDto.getPrice ().toString()

2021-11-16 16:36 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
try it pls. >>>>>>>>jsonPath("$.price").value(priceDto.getPrice())<<<<<<<<<  ^-^

2021-11-16 16:41 UTC, SofiiaOlenyn commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                .andExpect(jsonPath("$.price", equalTo(Integer.valueOf(String.valueOf(priceDto.getPrice())))));
It works, thank you very much :)))

2021-11-16 17:29 UTC, MuchosChuchos commented
I recommend you to read staff about git that Maks Kit have sent in our chat

2021-11-20 14:15 UTC, sergvasylchak submitted a review, later dismissed

2021-11-20 22:46 UTC, Oleksandr-Eleks requested changes

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +    private final String CONTENT = "{\"price\": 11 , \"externalId\": \"11\" }";
Please use text block here.

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +        price1.setExternalId("11");
Please extract "11" into the constant

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +                        .content(CONTENT)).andExpect(status().isOk())
Please start ".andExpect..." from a new line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-20 22:46 UTC, Oleksandr-Eleks commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerTest.java
> +
Please remove this blank line

2021-11-21 08:12 UTC, MuchosChuchos submitted a review, later dismissed

2021-11-21 10:50 UTC, MuchosChuchos commented
we should merge #104 at first and then this PR

2021-11-22 09:49 UTC, Oleksandr-Eleks approved these changes

2021-11-22 10:32 UTC, Anna-Kudiakova approved these changes

2021-11-22 17:37 UTC, MariamnaKh approved these changes

2021-11-23 09:52 UTC, merged