Add integration tests for controllers
Oleksandr-Eleks/pharmagator pull request #89
Opened 2021-11-13 15:07 UTC by Anna-Kudiakova

2021-11-13 16:10 UTC, MuchosChuchos reviewed
the first thing that caught my eye

2021-11-13 16:10 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/MedicineControllerIT_dataset.xml
> +</dataset>
leave blank line here, pls

2021-11-13 16:10 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +</dataset>
blank line ^-^

2021-11-13 18:44 UTC, Anna-Kudiakova commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/MedicineControllerIT_dataset.xml
> +</dataset>
Done!

2021-11-13 18:45 UTC, Anna-Kudiakova commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +</dataset>
done=)

2021-11-13 18:48 UTC, SofiiaOlenyn approved these changes

2021-11-13 19:14 UTC, MuchosChuchos requested changes

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT.java
> +    private final String uri = "/pharmacies";
pls make it in upper-case

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT.java
> +        final int pharmacyId = 2021111201;
make it non-final or upper-case, please

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT.java
> +        final int pharmacyId = 2021111203;
make it non-final or upper-case, pls

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT.java
> +        final int pharmacyId = 2021111201;
pls, make it non-final or upper-case

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT.java
> +        final int pharmacyId = 2021111201;
non-final or upper

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +    private final String uri = "/prices";
non-final or upper-case

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int pharmacyId = 2021111201;
upper-case or non-final

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int medicineId = 2021111201;
non-final or upper-case pls

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int pharmacyId = 2021110703;
take look

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int medicineId = 2021110703;
take look pls

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int pharmacyId = 2021111201;
take look pls

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int medicineId = 2021111201;
same as prev

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int pharmacyId = 2021111201;
another one =)

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int medicineId = 2021111201;
take look pls

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/MedicineControllerIT_dataset.xml
> +    <medicines id="2021111201" title="MedicineControllerIT_name1"></medicines>
use non-container tags here

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/MedicineControllerIT_dataset.xml
> +    <medicines id="2021111202" title="MedicineControllerIT_name2"></medicines>
the same as prev

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT_dataset.xml
> +    <pharmacies id="2021111201" name="PharmacyControllerIT_name1" medicine_link_template ="PharmacyControllerIT_link1"></pharmacies>
non-container tag

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PharmacyControllerIT_dataset.xml
> +    <pharmacies id="2021111202" name="PharmacyControllerIT_name2" medicine_link_template ="PharmacyControllerIT_link2"></pharmacies>
non-container tag pls ))

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +    <pharmacies id="2021111201" name="PharmacyControllerIT_name1" medicine_link_template ="PharmacyControllerIT_link1"></pharmacies>
convert to non-container tag pls

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +    <pharmacies id="2021111202" name="PharmacyControllerIT_name2" medicine_link_template ="PharmacyControllerIT_link2"></pharmacies>
the same as prev.

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +    <medicines id="2021111201" title="MedicineControllerIT_name1"></medicines>
same

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +    <medicines id="2021111202" title="MedicineControllerIT_name2"></medicines>
same

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +    <prices pharmacy_id="2021111201" medicine_id="2021111201" price="150" external_id ="2021111201"></prices>
same

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/resources/com/eleks/academy/pharmagator/controllers/PriceControllerIT_dataset.xml
> +    <prices pharmacy_id="2021111202" medicine_id="2021111202" price="200" external_id ="2021111202"></prices>
same

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int pharmacyId = 2021111201;
DRY. You can make it global

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +        final int medicineId = 2021111201;
DRY.))))

2021-11-13 19:14 UTC, MuchosChuchos commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +                    .andExpect(jsonPath("$.externalId").value("2021111201"));
this value is stored in a variable, hence you can not use string literal.

2021-11-13 21:28 UTC, Anna-Kudiakova commented on api/src/test/java/com/eleks/academy/pharmagator/controllers/PriceControllerIT.java
> +                    .andExpect(jsonPath("$.externalId").value("2021111201"));
fixed

2021-11-13 21:32 UTC, SofiiaOlenyn approved these changes

2021-11-14 06:07 UTC, MuchosChuchos approved these changes

2021-11-16 08:43 UTC, Oleksandr-Eleks commented
@Mykhailo-Cholii and @sergvasylchak , please approve if You have no more comments. Ready to merge! ;)

2021-11-19 14:12 UTC, sergvasylchak approved these changes

2021-11-19 14:35 UTC, merged